# Data Generation Configuration
debug: false
debug_config_path: null

# Model parameters
model_name: "gpt2" #"meta-llama/Llama-2-7b-hf"
target_model: "gpt2" #"meta-llama/Llama-2-7b-hf"

# Dataset parameters
dataset_name: "wikitext-2-raw-v1"
dataset_config_name: null  # The configuration name of the dataset to use (via the datasets library)
cache_path: "./cache"
use_dataset_cache: true
packing: true

# Data processing parameters
block_size: 128
preprocessing_num_workers: 1
validation_split_percentage: 0.1  # The percentage of the train set used as validation set in case there's no validation split

local_files_only: false